services:
  newsletter:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      APP_DATABASE__HOST: postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
