application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: "127.0.0.1"
  port: 5432
  name: "newsletter"
  username: "postgres"
  password: "password"
email_client:
  base_url: "localhost"
  sender_email: "sender@example.com"
  authorization_token: "sample-secret-token"
  timeout_milliseconds: 10000
